environment:
  matrix:
    # Hyper-V
    # =======

    - job_name: VS 2019 on Hyper-V
      APPVEYOR_BUILD_WORKER_IMAGE: vs2019-master
      APPVEYOR_BAKE_IMAGE: vs2019-master

    # GCE
    # =======

    # - job_name: VS 2019 on GCE us-central1
    #   APPVEYOR_BUILD_WORKER_IMAGE: vs2019-master-gce-us-central1
    #   APPVEYOR_BAKE_IMAGE: vs2019-master-gce-us-central1

    # # Azure
    # # =======

    # - job_name: VS 2019 on Azure West US
    #   APPVEYOR_BUILD_WORKER_IMAGE: vs2019-master-azure-westus
    #   APPVEYOR_BAKE_IMAGE: vs2019-master-azure-westus

init:
  - appveyor version
  - ps: $ErrorActionPreference = 'Stop'
  - ps: $env:cloud_type = (Get-ItemProperty "HKLM:\Software\AppVeyor\Build Agent").Mode
  - ps: 'Write-Host "OS Build: $((Get-CimInstance Win32_OperatingSystem).BuildNumber)"'
  - ps: $env:path.split(";")

clone_folder: '%USERPROFILE%\image-bake-scripts'

clone_script:
  - ps: Invoke-WebRequest "https://github.com/appveyor/build-images/archive/$($env:APPVEYOR_REPO_COMMIT).zip" -OutFile "$env:temp\scripts.zip"
  - ps: Expand-Archive -Path "$env:temp\scripts.zip" -DestinationPath "$env:temp\scripts" -Force
  - ps: Copy-Item -Path "$env:temp\scripts\build-images-$($env:APPVEYOR_REPO_COMMIT)\scripts\Windows\*" -Destination $env:APPVEYOR_BUILD_FOLDER -Recurse

test: off

# on_failure:
# - ps: Get-EventLog AppVeyor -newest 10 | Format-List

build_script:
  #- ps: if ($env:cloud_type -eq 'Azure' -or $env:cloud_type -eq 'HyperV') { .\extend_system_volume.ps1 }
  #- ps: .\fix_ruby.ps1
  #- ps: .\install_selenium_drivers.ps1
  #- ps: .\install_dotnet_core_sdks.ps1
  #- ps: .\set_java_home.ps1
  #- ps: .\install_android_sdk.ps1
  #- appveyor PushArtifact %TEMP%\android-sdkmanager.log.zip

 # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  #- ps: .\fix_ruby.ps1
  #- ps: .\install_dotnet_core_sdks.ps1
  #- ps: .\install_qt_fast_windows.ps1
  #- dir C:\Qt\6.2.2
  #- dir C:\Qt\Tools
  #- dir C:\Qt\Tools\QtInstallerFramework
  #- ps: .\install_nodejs_latest.ps1
  #- ps: .\install_boost_1.77.0_vs2019.ps1
  #- ps: .\fix_qt_symlinks.ps1
  #- ps: .\install_mingw.ps1
  - ps: .\install_wix.ps1
  - ps: .\install_wix_toolset_vs2019.ps1
  #- ps: Remove-Path "${env:ProgramFiles}\Eclipse Foundation\jdk-8.0.302.8-hotspot\bin" -ErrorAction Stop
  # Restart VM
  # - ps: Start-Sleep -s 5; Restart-Computer -Force
  # - ps: Start-Sleep -s 5
  #- ps: New-Item -ItemType SymbolicLink -Path "C:\Qt\6.5" -Target "C:\Qt\6.5.1" -Force | Out-Null

  - appveyor version
  - ps: .\cleanup_windows.ps1
