environment:
  matrix:
    # Hyper-V
    # =======

    # - job_name: VS 2022 on Hyper-V
    #   APPVEYOR_BUILD_WORKER_IMAGE: vs2022-master
    #   APPVEYOR_BAKE_IMAGE: vs2022-master

    # GCE
    # =======

    - job_name: VS 2022 on GCE us-central1
      APPVEYOR_BUILD_WORKER_IMAGE: vs2022-master-gce-us-central1
      APPVEYOR_BAKE_IMAGE: vs2022-master-gce-us-central1

    # Azure
    # =======

    # - job_name: VS 2022 on Azure West US
    #   APPVEYOR_BUILD_WORKER_IMAGE: vs2022-master-azure-westus
    #   APPVEYOR_BAKE_IMAGE: vs2022-master-azure-westus

init:
  - appveyor version
  #- ps: $ErrorActionPreference = 'Stop'
  - ps: $env:cloud_type = (Get-ItemProperty "HKLM:\Software\AppVeyor\Build Agent").Mode
  - ps: 'Write-Host "OS Build: $((Get-CimInstance Win32_OperatingSystem).BuildNumber)"'

clone_folder: '%USERPROFILE%\image-bake-scripts'

clone_script:
  - ps: Invoke-WebRequest "https://github.com/appveyor/build-images/archive/$($env:APPVEYOR_REPO_COMMIT).zip" -OutFile "$env:temp\scripts.zip"
  - ps: Expand-Archive -Path "$env:temp\scripts.zip" -DestinationPath "$env:temp\scripts" -Force
  - ps: Copy-Item -Path "$env:temp\scripts\build-images-$($env:APPVEYOR_REPO_COMMIT)\scripts\Windows\*" -Destination $env:APPVEYOR_BUILD_FOLDER -Recurse

test: off

# on_failure:
# - ps: Get-EventLog AppVeyor -newest 10 | Format-List

build_script:
  #- ps: .\install_dotnet_core_sdks.ps1
  # - ps: .\install_qt_ifw_windows.ps1
  #- ps: .\install_python.ps1
  - ps: .\install_coverity.ps1
  #- ps: .\install_flutter.ps1
  #- ps: .\extend_system_volume.ps1 
  # - ps: >-
  #       $items = Get-ChildItem -LiteralPath "C:\Qt" -Force -Recurse

  #       foreach ($item in $items) {
  #           if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) {
  #           cmd /c rmdir "$($item.FullName)" 2>$null
  #           cmd /c del "$($item.FullName)" 2>$null
  #         }
  #       }
  #- ps: Remove-Item -LiteralPath "C:\Qt\6.9.2" -Recurse -Force
  #- ps: Remove-Item -LiteralPath "C:\Qt\6.8.3" -Recurse -Force
  #- ps: Remove-Item -LiteralPath "C:\Qt\6.5.3" -Recurse -Force
  #- ps: .\install_qt_fast_windows.ps1
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  # - ps: Add-Path "${env:ProgramFiles}\Erlang OTP\bin"
  # - ps: |
  #     [Environment]::SetEnvironmentVariable("ERLANG_HOME", "${env:ProgramFiles}\Erlang OTP", "Machine")
  # - dir C:\Qt\6.2
  # - dir C:\Qt\Tools
  # - dir C:\Qt\Tools\QtInstallerFramework
  #- ps: .\add_ssh_known_hosts.ps1
  
  # - ps: .\install_qt_fast_windows.ps1
  # - ps: ./install_octo.ps1
  #- ps: .\install_go.ps1
  #- ps: ./install_nodejs_latest.ps1
  #- ps: ./install_selenium_drivers.ps1
  #- ps: ./install_mingw.ps1
  #- ps: .\install_nunit3.ps1
  #  Restart VM
  #  - ps: Start-Sleep -s 5; Restart-Computer -Force
  # - ps: Start-Sleep -s 5

  # - ps: .\install_sql_server_2022.ps1
  # - ps: Start-Sleep -s 5; Restart-Computer
  # - ps: Start-Sleep -s 5
  # - ps: .\install_sql_server_2022_after_restart.ps1
  # - ps: choco feature enable -n allowGlobalConfirmation

  - appveyor version
  - ps: .\cleanup_windows.ps1

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))