environment:
  matrix:
    # - job_name: Ubuntu 22.04 on Hyper-V
    #   APPVEYOR_BUILD_WORKER_IMAGE: ubuntu2204-master
    #   APPVEYOR_BAKE_IMAGE: ubuntu2204-master

    # - job_name: Ubuntu 20.04 on Hyper-V
    #   APPVEYOR_BUILD_WORKER_IMAGE: ubuntu2004-master
    #   APPVEYOR_BAKE_IMAGE: ubuntu2004-master

    - job_name: Ubuntu 18.04 on Hyper-V
      APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804-master
      APPVEYOR_BAKE_IMAGE: ubuntu1804-master

    # - job_name: Ubuntu 16.04 on Hyper-V
    #   APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1604-master
    #   APPVEYOR_BAKE_IMAGE: ubuntu1604-master

    # - job_name: Ubuntu 22.04 on GCE us-central1
    #   APPVEYOR_BUILD_WORKER_IMAGE: ubuntu2204-master-gce-us-central1
    #   APPVEYOR_BAKE_IMAGE: ubuntu2204-master-gce-us-central1

    # - job_name: Ubuntu 20.04 on GCE us-central1
    #   APPVEYOR_BUILD_WORKER_IMAGE: ubuntu2004-master-gce-us-central1
    #   APPVEYOR_BAKE_IMAGE: ubuntu2004-master-gce-us-central1

    # - job_name: Ubuntu 18.04 on GCE us-central1
    #   APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804-master-gce-us-central1
    #   APPVEYOR_BAKE_IMAGE: ubuntu1804-master-gce-us-central1

    # - job_name: Ubuntu 16.04 on GCE us-central1
    #   APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1604-master-gce-us-central1
    #   APPVEYOR_BAKE_IMAGE: ubuntu1604-master-gce-us-central1

  BASE_DIR: src/build-images-${APPVEYOR_REPO_COMMIT}/scripts/Ubuntu
  BOOTSTRAP: true
  #APPVEYOR_CONSOLE_DISABLE_PTY: true

clone_folder: ${HOME}/bake-scripts

init:
  - appveyor version
  - source /etc/os-release && echo $PRETTY_NAME

clone_script:
  - curl -fsSL "https://github.com/appveyor/build-images/archive/$APPVEYOR_REPO_COMMIT.tar.gz" -o scripts.tar.gz
  - mkdir src && tar -zxf scripts.tar.gz -C $APPVEYOR_BUILD_FOLDER/src

build_script:
  - cd $BASE_DIR && pwd
  - sudo -E ./fixconfig.sh
  #- sudo cp /opt/octopus/octo /usr/bin
  - appveyor PushArtifact versions.log

test: off
#on_failure:
#- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e
